"ruby.lint": {
  "standard": {
    "command": "standard",  // setting this will override automatic detection
    "useBundler": true,
    "only": ["array", "of", "cops", "to", "run"],
    "except": ["array", "of", "cops", "not", "to", "run"],
    "require": ["array", "of", "ruby", "files", "to, "require"]
  }
}