# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8cc807ae6d6cfdf2e2f322eb7b7e6b9ebc217f5c3eccfba985a381a8dd8b0fdf952acfb8cd8060c29cc9c6cc4e32cc1a5a70b0b30f717caf37dbc5703ef6f6c

test:
  secret_key_base: a9842b67be51f67169187cbb63d9c7e65eff2c5ca1f6a2e48bcd16b38e00bfb9ad50c7189871f2a4bc1437b7da4adff3671dccf18ab4570d19dfe6beb5e089c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
